name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  prod_ip_ubuntu: 192.168.1.112

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.cc }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webui
    
  deploy:
   if: github.ref != 'refs/heads/master'
   runs-on: ubuntu-latest
   needs: build
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Set up SSH key
     uses: webfactory/ssh-agent@v0.5.0
     with:
       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
   - name: Install dependencies
     run: |
       sudo apt-get update && \
       sudo apt-get install -y ansible
   - name: Deploy app
     env:
       DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/myapp
       DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     run: |
       ansible-playbook --user ${{ secrets.SSH_USER }} -i inventory.yml playbook.yml
